package com.pinelabs.pluralsdk.utils

import com.pinelabs.pluralsdk.utils.Constants.Companion.BASE_IMAGES

class BankConstant {
    companion object {
        const val AXIS = BASE_IMAGES+"axis_bank.svg"
        const val HDFC = BASE_IMAGES+"hdfc_bank.svg"
        const val JK = BASE_IMAGES+"jk_bank.svg"
        const val ICICI = BASE_IMAGES+"icici_bank.svg"
        const val FEDERAL = BASE_IMAGES+"federal_bank.svg"
        const val KARNATAKA = BASE_IMAGES+"karnataka_bank.svg"
        const val CORPORATION = BASE_IMAGES+"corporation_bank.svg"
        const val INDIAN = BASE_IMAGES+"indian_bank.svg"
        const val YES = BASE_IMAGES+"yes_bank.svg"
        const val CENTRAL = BASE_IMAGES+"central_bank.svg"
        const val KOTAK = BASE_IMAGES+"kotak_bank.svg"
        const val ORIENTAL = BASE_IMAGES+"oriental_bank.png"
        const val UNITED_BANK = BASE_IMAGES+"united_bank_of_india.png"
        const val INDIAN_OVERSEAS = BASE_IMAGES+"indian_overseas_bank.svg"
        const val CITY_UNION = BASE_IMAGES+"city_union_bank.svg"
        const val UNION_BANK = BASE_IMAGES+"union_bank_of_india.svg"
        const val CANARA_BANK = BASE_IMAGES+"canara_bank.svg"
        const val MAHARASHTRA_BANK = BASE_IMAGES+"bank_of_maharashtra.svg"
        const val CATHOLIC_SYRIAN = BASE_IMAGES+"catholic_syrian_bank.svg"
        const val DHANALAKSHMI = BASE_IMAGES+"dhanalakshmi_bank.svg"
        const val ANDHRA = BASE_IMAGES+"andhra_bank.svg"
        const val VIJAYA = BASE_IMAGES+"vijaya_bank.png"
        const val SARASWAT = BASE_IMAGES+"saraswat_bank.svg"
        const val PNB = BASE_IMAGES+"punjab_national_bank.svg"
        const val UCO = BASE_IMAGES+"uco_bank.svg"
        const val PUNJAB_AND_SINDH = BASE_IMAGES+"punjab_and_sindh_bank.svg"
        const val INDUSIND = BASE_IMAGES+"indusind.svg"
        const val TAMINAD_MERCHANTILE = BASE_IMAGES+"tamilnad_mercantile_bank.svg"
        const val COSMOS = BASE_IMAGES+"cosmos_bank.svg"
        const val PNB_CORPORATE = BASE_IMAGES+"punjab_national_bank.svg"
        const val ANDHRA_CORPORATE = BASE_IMAGES+"andhra_bank.svg"
        const val BARODA = BASE_IMAGES+"bank_of_baroda.svg"
        const val BAHRAIN_KUWAIT = BASE_IMAGES+"bank_of_bahrain_and_kuwait.svg"
        const val BARODA_RETAIL = BASE_IMAGES+"bank_of_baroda.svg"
        const val DEDUSHE = BASE_IMAGES+"deutsche_bank.svg"
        const val DEVELOPMENT = BASE_IMAGES+"development_credit_bank.svg"
        const val DENA = BASE_IMAGES+"dena_bank.svg"
        const val IDBI = BASE_IMAGES+"idbi_bank.svg"
        const val KARUR = BASE_IMAGES+"karur_vysya_bank.svg"
        const val LAXMI_VILAS = BASE_IMAGES+"laxmi_vilas_bank.svg"
        const val LAXMI_VILAS_RETAIL = BASE_IMAGES+"laxmi_vilas_bank.svg"
        const val PUNJAB_MAHARASHTRA = BASE_IMAGES+"punjab_and_maharashtra.png"
        const val STANDARD_CHARTERED_BANK = BASE_IMAGES+"standard_chartered_bank.svg"
        const val SOUTH_INDIAN_BANK = BASE_IMAGES+"south_indian_bank.svg"
        const val SHAMRO = BASE_IMAGES+"shamro.png"
        const val SYNDICATE = BASE_IMAGES+"syndicate_bank.svg"
        const val TAMIL_NADU_STATE_COORP = BASE_IMAGES+"tamil_nadu.png"
        const val JANATA = BASE_IMAGES+"janata.png"
        //const val NKGSB = BASE_IMAGES+"nkgsb_co_op_bank.svg"
        const val TJSB = BASE_IMAGES+"tjsb.png"
        const val KALYAN_JANATA = BASE_IMAGES+"kalyan_janata.png"
        const val MEHSANA = BASE_IMAGES+"mehsana.svg"
        const val BANDHAN = BASE_IMAGES+"bandhan_bank.svg"
        //const val DIGIBANK = BASE_IMAGES+".svg"
        const val IDFC = BASE_IMAGES+"idfc_first_bank.svg"
        const val BASSIEN = BASE_IMAGES+"bassien.png"
        //const val PNB_YUVA = BASE_IMAGES+".svg"
        const val RBL = BASE_IMAGES+"rbl_bank_limited.svg"
        const val KALUPUR = BASE_IMAGES+"kalupur.png"
        //const val EQUITAS = BASE_IMAGES+"equitas_small_finance_bank.svg"
        const val THANE = BASE_IMAGES+"thane.png"
        const val SURYODAY = BASE_IMAGES+"suryoday.png"
        const val ESAF = BASE_IMAGES+"esaf_small_finance_bank.svg"
        const val VARACHHA = BASE_IMAGES+"varacha.png"
        const val NORTH_EAST = BASE_IMAGES+"north_east.png"
        const val IDBI_CORPORATE = BASE_IMAGES+"idbi_bank.svg"
        const val YES_CORPORATE = BASE_IMAGES+"yes_bank.svg"
        const val CORPORATION_CORPORATE = BASE_IMAGES+"corporation_bank.svg"
        const val RBL_CORPORATE = BASE_IMAGES+"rbl_bank_limited.svg"
        const val SHAMRO_CORPORATE = BASE_IMAGES+"shamro.png"
        const val DHANLAKSHMI = BASE_IMAGES+"dhanalakshmi_bank.svg"
        const val BARCLAYS = BASE_IMAGES+"barclays_bank.svg"
        const val ZOROASTRAIN = BASE_IMAGES+"zoroastrian.png"
        const val AU = BASE_IMAGES+"au_small_finance_bank.svg"
        const val ALLAHABAD = BASE_IMAGES+"allahabad_bank.svg"
        const val SBI = BASE_IMAGES+"state_bank_of_india.svg"
        const val FINCARE = BASE_IMAGES+"fincare.png"
        const val BANDHAN_CORPORATE = BASE_IMAGES+"bandhan_bank.svg"
        const val KARNATAKA_GRAMIN = BASE_IMAGES+"karnataka_gramin.png"
        const val DEFAULT = BASE_IMAGES
    }
}