package com.pinelabs.pluralsdk.utils

import com.pinelabs.pluralsdk.R

enum class NBBANKS(var bankCode: Int, var bankName: String?, var bankImage: String) {
    AXIS(R.string.axis_bank_code, "", BankConstant.AXIS),
    HDFC(R.string.hdfc_bank_code, "", BankConstant.HDFC),
    JK(R.string.jk_bank_code, "", BankConstant.JK),
    ICICI(R.string.icici_bank_code, "", BankConstant.ICICI),
    FEDERAL(R.string.federal_bank_code, "", BankConstant.FEDERAL),
    KARNATAKA(R.string.karnataka_bank_code, "", BankConstant.KARNATAKA),
    CORPORATION(R.string.corporation_bank_code, "", BankConstant.CORPORATION),
    INDIAN(R.string.indian_bank_code, "", BankConstant.INDIAN),
    YES(R.string.yes_bank_code, "", BankConstant.YES),
    CENTRAL(R.string.central_bank_code, "", BankConstant.CENTRAL),
    KOTAK(R.string.kotak_bank_code, "", BankConstant.KOTAK),
    ORIENTAL(R.string.oriental_bank_code, "", BankConstant.ORIENTAL),
    UNITED_BANK(R.string.united_bank_code, "", BankConstant.UNITED_BANK),
    INDIAN_OVERSEAS(R.string.indian_overseas_bank_code, "", BankConstant.INDIAN_OVERSEAS),
    CITY_UNION(R.string.city_union_bank_code, "", BankConstant.CITY_UNION),
    UNION_BANK(R.string.union_bank_code, "UNION", BankConstant.UNION_BANK),
    CANARA_BANK(R.string.canara_bank_code, "", BankConstant.CANARA_BANK),
    MAHARASHTRA_BANK(R.string.maharashtra_bank_code, "", BankConstant.MAHARASHTRA_BANK),
    CATHOLIC_SYRIAN(R.string.catholic_syrian_bank_code, "", BankConstant.CATHOLIC_SYRIAN),
    DHANALAKSHMI(R.string.dhanlaxmi_bank_code, "", BankConstant.DHANALAKSHMI),
    ANDHRA(R.string.andhra_bank_code, "", BankConstant.ANDHRA),
    VIJAYA(R.string.vijaya_bank_code, "", BankConstant.VIJAYA),
    SARASWAT(R.string.saraswat_bank_code, "", BankConstant.SARASWAT),
    PNB(R.string.pnb_bank_code, "", BankConstant.PNB),
    UCO(R.string.uco_bank_code, "", BankConstant.UCO),
    PUNJAB_AND_SINDH(R.string.punjab_and_sindh_bank_code, "", BankConstant.PUNJAB_AND_SINDH),
    INDUSIND(R.string.indusind_bank_code, "", BankConstant.INDUSIND),
    TAMINAD_MERCHANTILE(R.string.tamilnad_merchantile_bank_code, "", BankConstant.TAMINAD_MERCHANTILE),
    COSMOS(R.string.cosmos_bank_code, "", BankConstant.COSMOS),
    PNB_CORPORATE(R.string.pnb_corporate_bank_code, "", BankConstant.PNB_CORPORATE),
    ANDHRA_CORPORATE(R.string.andhra_corporate_bank_code, "", BankConstant.ANDHRA_CORPORATE),
    BARODA(R.string.baroda_bank_code, "", BankConstant.BARODA),
    BAHRAIN_KUWAIT(R.string.bahrain_and_kuwait_bank_code, "", BankConstant.BAHRAIN_KUWAIT),
    BARODA_RETAIL(R.string.baroda_retail_bank_code, "", BankConstant.BARODA_RETAIL),
    DEDUSHE(R.string.dedusche_bank_code, "", BankConstant.DEDUSHE),
    DEVELOPMENT(R.string.development_credit_bank_code, "", BankConstant.DEVELOPMENT),
    DENA(R.string.dena_bank_code, "", BankConstant.DENA),
    IDBI(R.string.idbi_bank_code, "", BankConstant.IDBI),
    KARUR(R.string.karur_vysya_bank_code, "", BankConstant.KARUR),
    LAXMI_VILAS(R.string.laxmi_vilas_bank_code, "", BankConstant.LAXMI_VILAS),
    LAXMI_VILAS_RETAIL(R.string.laxmi_vilas_bank_retail_code, "", BankConstant.LAXMI_VILAS_RETAIL),
    PUNJAB_MAHARASHTRA(R.string.punjab_maharashtra_bank_code, "", BankConstant.PUNJAB_MAHARASHTRA),
    STANDARD_CHARTERED_BANK(R.string.standard_chartered_bank_code, "", BankConstant.STANDARD_CHARTERED_BANK),
    SOUTH_INDIAN_BANK(R.string.south_indian_bank_code, "", BankConstant.SOUTH_INDIAN_BANK),
    SHAMRO(R.string.shamro_vithal_bank_code, "", BankConstant.SHAMRO),
    SYNDICATE(R.string.syndicate_bank_code, "", BankConstant.SYNDICATE),
    TAMIL_NADU_STATE_COORP(R.string.tamil_nadu_state_coop_bank_code, "", BankConstant.TAMIL_NADU_STATE_COORP),
    JANATA(R.string.janata_sahakari_bank_code, "", BankConstant.JANATA),
    /*NKGSB(R.string.nkgsb_bank_code, "", BankConstant.NKGSB),*/
    TJSB(R.string.tjsb_bank_code, "", BankConstant.TJSB),
    KALYAN_JANATA(R.string.kalyan_janata_bank_code, "", BankConstant.KALYAN_JANATA),
    MEHSANA(R.string.mehsana_urban_bank_code, "", BankConstant.MEHSANA),
    BANDHAN(R.string.bandhan_bank_code, "", BankConstant.BANDHAN),
    //DIGIBANK(R.string.digibank_bank_code,"",R.drawable.),
    IDFC(R.string.idfc_first_bank_code, "", BankConstant.IDFC),
    BASSIEN(R.string.bassien_bank_code, "", BankConstant.BASSIEN),
    //PNB_YUVA(R.string.pnb_bank_code,"",R.drawable.),
    RBL(R.string.rbl_bank_code, "", BankConstant.RBL),
    KALUPUR(R.string.the_kalupur_bank_code, "", BankConstant.KALUPUR),
    //EQUITAS(R.string.equitas_bank_code,"",EQUITAS),
    THANE(R.string.thane_bharat_bank_code, "", BankConstant.THANE),
    SURYODAY(R.string.suryoday_bank_code, "", BankConstant.SURYODAY),
    ESAF(R.string.esaf_bank_code, "", BankConstant.ESAF),
    VARACHHA(R.string.varachha_bank_code, "", BankConstant.VARACHHA),
    NORTH_EAST(R.string.north_east_bank_code, "", BankConstant.NORTH_EAST),
    IDBI_CORPORATE(R.string.idbi_corporate_bank_code, "", BankConstant.IDBI_CORPORATE),
    YES_CORPORATE(R.string.yes_corporate_bank_code, "", BankConstant.YES_CORPORATE),
    CORPORATION_CORPORATE(R.string.corporation_corporate_bank_code, "", BankConstant.CORPORATION_CORPORATE),
    RBL_CORPORATE(R.string.rbl_corporate_bank_code, "", BankConstant.RBL_CORPORATE),
    SHAMRO_CORPORATE(R.string.shamro_vithal_corporate_bank_code, "", BankConstant.SHAMRO_CORPORATE),
    DHANLAKSHMI(R.string.dhanlaxmi_corporate_bank_code, "", BankConstant.DHANLAKSHMI),
    BARCLAYS(R.string.barclays_bank_code, "", BankConstant.BARCLAYS),
    ZOROASTRAIN(R.string.zoroastrain_bank_code, "", BankConstant.ZOROASTRAIN),
    AU(R.string.au_small_finance_bank_code, "", BankConstant.AU),
    ALLAHABAD(R.string.allahabad_bank_code, "", BankConstant.ALLAHABAD),
    SBI(R.string.sbi_bank_code, "", BankConstant.SBI),
    FINCARE(R.string.fincare_bank_code, "", BankConstant.FINCARE),
    BANDHAN_CORPORATE(R.string.bandhan_bank_corporate_code, "", BankConstant.BANDHAN_CORPORATE),
    KARNATAKA_GRAMIN(R.string.karnataka_gramin_bank_code, "", BankConstant.KARNATAKA_GRAMIN),
    DEFAULT(R.string.default_bank_code, "", BankConstant.DEFAULT)
}
