package com.pinelabs.pluralsdk.utils

import com.pinelabs.pluralsdk.R

enum class NBBANKS(var bankCode: Int, var bankName: String, val bankImage: Int) {
    AXIS(R.string.axis_bank_code, "", R.drawable.axis_bank),
    HDFC(R.string.hdfc_bank_code, "", R.drawable.hdfc_bank),
    JK(R.string.jk_bank_code,"", R.drawable.jk_bank),
    ICICI(R.string.icici_bank_code,"",R.drawable.icici_bank),
    FEDERAL(R.string.federal_bank_code,"",R.drawable.federal_bank),
    KARNATAKA(R.string.karnataka_bank_code,"",R.drawable.karnataka_bank),
    CORPORATION(R.string.corporation_bank_code,"",R.drawable.corporation_bank),
    INDIAN(R.string.indian_bank_code,"",R.drawable.indian_bank),
    YES(R.string.yes_bank_code,"",R.drawable.yes_bank),
    CENTRAL(R.string.central_bank_code,"",R.drawable.central_bank),
    KOTAK(R.string.kotak_bank_code,"",R.drawable.kotak_bank),
    ORIENTAL(R.string.oriental_bank_code,"",R.drawable.oriental_bank),
    UNITED_BANK(R.string.united_bank_code,"",R.drawable.united_bank_of_india),
    INDIAN_OVERSEAS(R.string.indian_overseas_bank_code,"",R.drawable.indian_overseas_bank),
    CITY_UNION(R.string.city_union_bank_code,"",R.drawable.city_union_bank),
    UNION_BANK(R.string.union_bank_code,"UNION",R.drawable.union_bank_of_india),
    CANARA_BANK(R.string.canara_bank_code,"",R.drawable.canara_bank),
    MAHARASHTRA_BANK(R.string.maharashtra_bank_code,"",R.drawable.bank_of_maharashtra),
    CATHOLIC_SYRIAN(R.string.catholic_syrian_bank_code,"",R.drawable.catholic_syrian_bank),
    DHANALAKSHMI(R.string.dhanlaxmi_bank_code,"",R.drawable.dhanalakshmi_bank),
    ANDHRA(R.string.andhra_bank_code,"",R.drawable.andhra_bank),
    VIJAYA(R.string.vijaya_bank_code,"",R.drawable.vijaya_bank),
    SARASWAT(R.string.saraswat_bank_code,"",R.drawable.saraswat_bank),
    PNB(R.string.pnb_bank_code,"",R.drawable.punjab_national_bank),
    UCO(R.string.uco_bank_code,"",R.drawable.uco_bank),
    PUNJAB_AND_SINDH(R.string.punjab_and_sindh_bank_code,"",R.drawable.punjab_and_sindh_bank),
    INDUSIND(R.string.indusind_bank_code,"",R.drawable.indusind),
    TAMINAD_MERCHANTILE(R.string.tamilnad_merchantile_bank_code,"",R.drawable.tamilnad_mercantile_bank),
    COSMOS(R.string.cosmos_bank_code,"",R.drawable.cosmos_bank),
    PNB_CORPORATE(R.string.pnb_corporate_bank_code,"",R.drawable.punjab_national_bank),
    ANDHRA_CORPORATE(R.string.andhra_corporate_bank_code,"",R.drawable.andhra_bank),
    BARODA(R.string.baroda_bank_code,"", R.drawable.bank_of_baroda),
    BAHRAIN_KUWAIT(R.string.bahrain_and_kuwait_bank_code,"",R.drawable.bank_of_bahrain_and_kuwait),
    BARODA_RETAIL(R.string.baroda_retail_bank_code,"",R.drawable.bank_of_baroda),
    DEDUSHE(R.string.dedusche_bank_code,"",R.drawable.deutsche_bank),
    DEVELOPMENT(R.string.development_credit_bank_code,"",R.drawable.development_credit_bank),
    //DENA(R.string.dena_bank_code,"",R.drawable.dena_bank),
    IDBI(R.string.idbi_bank_code,"",R.drawable.idbi_bank),
    KARUR(R.string.karur_vysya_bank_code,"",R.drawable.karur_vysya_bank),
    LAXMI_VILAS(R.string.laxmi_vilas_bank_code,"",R.drawable.laxmi_vilas_bank),
    LAXMI_VILAS_RETAIL(R.string.laxmi_vilas_bank_retail_code,"",R.drawable.laxmi_vilas_bank),
    PUNJAB_MAHARASHTRA(R.string.punjab_maharashtra_bank_code,"",R.drawable.punjab_and_maharashtra),
    STANDARD_CHARTERED_BANK(R.string.standard_chartered_bank_code,"",R.drawable.standard_chartered_bank),
    SOUTH_INDIAN_BANK(R.string.south_indian_bank_code,"",R.drawable.south_indian_bank),
    SHAMRO(R.string.shamro_vithal_bank_code,"",R.drawable.shamro),
    SYNDICATE(R.string.syndicate_bank_code,"",R.drawable.syndicate_bank),
    TAMIL_NADU_STATE_COORP(R.string.tamil_nadu_state_coop_bank_code,"",R.drawable.tamil_nadu),
    JANATA(R.string.janata_sahakari_bank_code,"",R.drawable.janata),
    //NKGSB(R.string.nkgsb_bank_code,"",R.drawable.nkgsb_co_op_bank),
    TJSB(R.string.tjsb_bank_code,"",R.drawable.tjsb),
    KALYAN_JANATA(R.string.kalyan_janata_bank_code,"",R.drawable.kalyan_janata),
    MEHSANA(R.string.mehsana_urban_bank_code,"",R.drawable.mehsana),
    BANDHAN(R.string.bandhan_bank_code,"",R.drawable.bandhan_bank),
    //DIGIBANK(R.string.digibank_bank_code,"",R.drawable.),
    IDFC(R.string.idfc_first_bank_code,"",R.drawable.idfc_first_bank),
    BASSIEN(R.string.bassien_bank_code,"",R.drawable.bassien),
    //PNB_YUVA(R.string.pnb_bank_code,"",R.drawable.),
    RBL(R.string.rbl_bank_code,"",R.drawable.rbl_bank_limited),
    KALUPUR(R.string.the_kalupur_bank_code,"",R.drawable.kalupur),
    //EQUITAS(R.string.equitas_bank_code,"",R.drawable.equitas_small_finance_bank),
    THANE(R.string.thane_bharat_bank_code,"",R.drawable.thane),
    SURYODAY(R.string.suryoday_bank_code,"",R.drawable.suryoday),
    ESAF(R.string.esaf_bank_code,"",R.drawable.esaf_small_finance_bank),
    VARACHHA(R.string.varachha_bank_code,"",R.drawable.varacha),
    NORTH_EAST(R.string.north_east_bank_code,"",R.drawable.north_east),
    IDBI_CORPORATE(R.string.idbi_corporate_bank_code,"",R.drawable.idbi_bank),
    YES_CORPORATE(R.string.yes_corporate_bank_code,"",R.drawable.yes_bank),
    CORPORATION_CORPORATE(R.string.corporation_corporate_bank_code,"",R.drawable.corporation_bank),
    RBL_CORPORATE(R.string.rbl_corporate_bank_code,"",R.drawable.rbl_bank_limited),
    SHAMRO_CORPORATE(R.string.shamro_vithal_corporate_bank_code,"",R.drawable.shamro),
    DHANLAKSHMI(R.string.dhanlaxmi_corporate_bank_code,"",R.drawable.dhanalakshmi_bank),
    BARCLAYS(R.string.barclays_bank_code,"",R.drawable.barclays_bank),
    ZOROASTRAIN(R.string.zoroastrain_bank_code,"",R.drawable.zoroastrian),
    AU(R.string.au_small_finance_bank,"",R.drawable.au_small_finance_bank),
    ALLAHABAD(R.string.allahabad_bank_code,"",R.drawable.allahabad_bank),
    SBI(R.string.sbi_bank_code,"",R.drawable.state_bank_of_india),
    FINCARE(R.string.fincare_bank_code,"",R.drawable.fincare),
    BANDHAN_CORPORATE(R.string.bandhan_bank_corporate_code,"",R.drawable.bandhan_bank),
    KARNATAKA_GRAMIN(R.string.karnataka_gramin_bank_code,"",R.drawable.karnataka_gramin),
    DEFAULT(R.string.default_bank_code, "",R.drawable.generic_bank)
}
